---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.10.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.10.0 - Language Matching Booster
  - NEW: TVDb artwork lookup with intelligent title matching during cache refresh
  - NEW: Language presets for Dutch, German, French, Spanish, Italian, Portuguese, Swedish, Norwegian, Danish, Polish
  - NEW: Configurable word translations (e.g., "Bouwers=Builders") for localized series titles
  - NEW: Article prefix substitution (e.g., "De Smurfen" -> "The Smurfen")
  - NEW: "And" word substitution (e.g., "Tom en Jerry" -> "Tom & Jerry")
  - NEW: API endpoints for language presets (/Xtream/Languages)
  - NEW: Separate JSON files per language for easy community contributions
  - EFFECT: 90%+ TVDb match rate for series with localized titles
  - EFFECT: High-quality artwork from TVDb, falls back to Xtream provider images

  v0.9.8.0 - Eager Jellyfin Database Population
  - NEW: Eagerly populates jellyfin.db after cache refresh for instant browsing
  - NEW: Iterates through all series, seasons, and episodes to pre-populate database
  - FIX: Continues population even when individual items have bad provider data
  - EFFECT: Browse series instantly without waiting for lazy loading
  - EFFECT: ~20-30 min population time for large libraries (666 series, 10k episodes)

  v0.9.7.0 - Cache Acceleration (3x faster sync)
  - NEW: Parallel series processing with configurable parallelism (default: 3 concurrent)
  - NEW: Request throttling to prevent rate limiting (configurable delay between requests)
  - NEW: UI sliders for parallelism (1-10) and throttle delay (0-500ms) in Series settings
  - PERF: Eliminated double series API calls by caching series lists during first pass
  - PERF: Added GetEpisodesFromSeriesInfo helper to avoid redundant API calls per season
  - PERF: HashSet-based episode deduplication (O(1) instead of O(n) lookups)
  - EFFECT: Cache refresh ~3x faster (666 series: 17 min -> 5 min with default settings)
  - EFFECT: Single API call per series instead of 1 + N (where N = number of seasons)

  v0.9.6.0 - HTTP Retry Handler and Missing Episodes Fix
  - NEW: HTTP retry with exponential backoff for transient API failures (HTTP 5xx)
  - NEW: Failure tracking service to skip known-bad URLs for 24 hours
  - NEW: Configurable retry settings (attempts, delay, failure cache TTL)
  - FIX: Missing episodes now found via two-phase lookup (dictionary key + Season property)
  - FIX: Episodes stored under wrong dictionary key are now discovered
  - EFFECT: Cache refresh completes with ~95% success rate (up from ~88%)
  - EFFECT: All episodes display correctly regardless of provider API structure

  v0.9.5.3 - Fix malformed JSON from Xtream API
  - FIX: Handle cases where Xtream API returns JSON array instead of object for series data
  - FIX: Prevents cache failures for series with malformed API responses
  - IMPROVEMENT: Better error logging for JSON deserialization failures
  - EFFECT: Series that previously failed to cache now load successfully with empty data

  v0.9.5.2 - Clear Cache now cleans up jellyfin.db
  - FIX: Clear Cache button now triggers Jellyfin channel refresh after invalidating plugin cache
  - EFFECT: When cache is cleared, plugin falls back to API, Jellyfin updates jellyfin.db with fresh data
  - EFFECT: Orphaned items in jellyfin.db are removed when they no longer exist in API response
  - Full cache clear cycle: Plugin cache cleared → Jellyfin refresh → API fetch → DB updated
