---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.4.8"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.4.8 - Configuration UI Error Handling Fix
  - FIXED: Error messages stacking on Series configuration page when revisiting without valid credentials
  - FIXED: Error messages not clearing when credentials are successfully configured
  - IMPROVED: Added proper error handling to VOD and Live TV configuration pages (previously silent failures)
