---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.1.5"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  - FIXED: Missing episodes in some series - Added fallback to search all episodes by Season property when dictionary lookup fails
  - This handles cases where episodes might be stored under different season ID keys in the API response
  - Fixed tag parsing for Unicode pipe characters (┃NL┃ tags now stripped from titles)
  - Fixed episodes not showing: Added explicit check for non-empty episodes collection
  - Fixed episodes not showing: Simplified GetEpisodes to use TryGetValue pattern correctly
  - Fixed missing episodes in series: Added configuration check and safe season lookup in GetEpisodes
  - Added flat VOD view feature: Show all movies directly without category folders
  - Added flat series view feature: Show all series directly without category folders
  - Both features are backward compatible and opt-in via configuration
