---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.2.7"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  - FIXED: Seasons not showing - now uses Seasons collection from API response instead of only Episodes dictionary keys
  - Added fallback logic to handle cases where Seasons collection is empty but Episodes dictionary has data
  - FIXED: JavaScript now properly displays detailed error messages from backend instead of generic "Failed" message
  - Improved error handling in credentials page to show specific connection error details
  - IMPROVED: Better error messages for provider connection failures - now shows specific error details instead of generic "Failed" message
  - Added detailed error handling in TestProvider endpoint to help diagnose connection issues
  - Error messages now indicate specific problems: hostname resolution, connection refused, timeout, etc.
  - CRITICAL FIX: Prevent plugin from crashing on startup when provider connection fails - channels now return empty results instead of throwing exceptions
  - Added defensive checks for plugin instance availability in channel initialization
  - Improved error handling in flattened view methods to gracefully handle API failures
  - CRITICAL FIX: Restored VOD and Series libraries - added error handling and fallback in ParseName to prevent channels from breaking
  - Fixed country code prefix filtering: Added null check and improved regex pattern to properly strip "| NL |" prefixes
  - Added country code prefix filtering: Automatically strips prefixes like "| NL |", "| DE |", etc. from series names for better metadata matching
  - Fixed episodes not showing: Added explicit check for non-empty episodes collection
  - Fixed episodes not showing: Simplified GetEpisodes to use TryGetValue pattern correctly
  - Fixed missing episodes in series: Added configuration check and safe season lookup in GetEpisodes
  - Added flat VOD view feature: Show all movies directly without category folders
  - Added flat series view feature: Show all series directly without category folders
  - Both features are backward compatible and opt-in via configuration
