---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.4.9"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.4.9 - Unicode Tag Parsing Fix & UX Improvements
  - FIXED: Unicode pipe characters (┃) not being stripped from series/movie titles - titles like "┃NL┃ Juliet" now display as "Juliet"
  - IMPROVED: User feedback when clicking cache buttons during active refresh
  - IMPROVED: Default cache refresh frequency changed from 1 hour to 10 hours (more reasonable for most users)
  - IMPROVED: Maximum refresh frequency limited to 23 hours to prevent cache expiration issues
