---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.14.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.14.0 - Delta-Based Database Population
  - PERF: Delta-based detection using ExternalId (channel GUID) matching
  - PERF: Fast path when database is fully populated (>95% threshold)
  - PERF: Verification samples first 5 series to confirm children exist
  - PERF: Parallel processing (5 concurrent) with 50ms throttling for new items
  - PERF: Robust error handling for Jellyfin channel API edge cases
  - EFFECT: Subsequent cache refreshes complete in ~6 seconds instead of minutes
  - EFFECT: New series are still fully populated with seasons and episodes

  v0.9.13.0 - TVDb Artwork Injection + Bug Fixes
  - NEW: Metadata language preference — TVDb queries use Jellyfin's server-wide preferred language
  - FIX: Season artwork now displays (ImageUrl was computed but never assigned to ChannelItemInfo)
  - FIX: Episode names now show parsed title instead of hardcoded "Episode N"
  - IMPROVED: Season image fallback chain: Xtream season cover → TVDb series poster → Xtream series cover
  - IMPROVED: Episode image fallback chain: Xtream episode → season cover → TVDb series poster → Xtream series cover
  - EFFECT: Seasons and episodes display artwork reliably via TVDb CDN fallback
  - NOTE: Per-episode TVDb images not available (Jellyfin API limitation) — see TODO.md for future options

  v0.9.12.0 - Caching Feature Hardening
  - FIX (CRITICAL): Prevent saving Series config when categories failed to load (was wiping category selection)
  - FIX: Include TVDb settings in cache hash — changing Title Overrides now correctly invalidates cache
  - FIX: Cancel running cache refresh before starting new one on config save (overrides now take effect immediately)
  - FIX: CancellationTokenSource disposal race condition in cache refresh (prevents ObjectDisposedException)
  - FIX: Database population errors now logged at WARNING level (first 10) instead of DEBUG for easier diagnosis

  v0.9.11.0 - Title Override Map (replaces Language Booster)
  - NEW: Title Override Map — map series titles directly to TVDb IDs for guaranteed artwork matches
  - NEW: Direct TVDb ID lookup bypasses search ambiguity entirely
  - CHANGED: Replaced Language Booster (presets, word translations, article/and substitution) with simple title overrides
  - REMOVED: Language preset system, 10 language JSON files, /Xtream/Languages API endpoints
  - KEPT: Name-based TVDb search for series without overrides
  - KEPT: Language indicator stripping (e.g., "(NL Gesproken)" removed before search)
  - EFFECT: Simpler configuration — just paste "SeriesTitle=TVDbID" for unmatched series
  - EFFECT: Find TVDb IDs at thetvdb.com (number in the series URL)

  v0.9.8.0 - Eager Jellyfin Database Population
  - NEW: Eagerly populates jellyfin.db after cache refresh for instant browsing
  - NEW: Iterates through all series, seasons, and episodes to pre-populate database
  - FIX: Continues population even when individual items have bad provider data
  - EFFECT: Browse series instantly without waiting for lazy loading
  - EFFECT: ~20-30 min population time for large libraries (666 series, 10k episodes)

  v0.9.7.0 - Cache Acceleration (3x faster sync)
  - NEW: Parallel series processing with configurable parallelism (default: 3 concurrent)
  - NEW: Request throttling to prevent rate limiting (configurable delay between requests)
  - NEW: UI sliders for parallelism (1-10) and throttle delay (0-500ms) in Series settings
  - PERF: Eliminated double series API calls by caching series lists during first pass
  - PERF: Added GetEpisodesFromSeriesInfo helper to avoid redundant API calls per season
  - PERF: HashSet-based episode deduplication (O(1) instead of O(n) lookups)
  - EFFECT: Cache refresh ~3x faster (666 series: 17 min -> 5 min with default settings)
  - EFFECT: Single API call per series instead of 1 + N (where N = number of seasons)

  v0.9.6.0 - HTTP Retry Handler and Missing Episodes Fix
  - NEW: HTTP retry with exponential backoff for transient API failures (HTTP 5xx)
  - NEW: Failure tracking service to skip known-bad URLs for 24 hours
  - NEW: Configurable retry settings (attempts, delay, failure cache TTL)
  - FIX: Missing episodes now found via two-phase lookup (dictionary key + Season property)
  - FIX: Episodes stored under wrong dictionary key are now discovered
  - EFFECT: Cache refresh completes with ~95% success rate (up from ~88%)
  - EFFECT: All episodes display correctly regardless of provider API structure

  v0.9.5.3 - Fix malformed JSON from Xtream API
  - FIX: Handle cases where Xtream API returns JSON array instead of object for series data
  - FIX: Prevents cache failures for series with malformed API responses
  - IMPROVEMENT: Better error logging for JSON deserialization failures
  - EFFECT: Series that previously failed to cache now load successfully with empty data

  v0.9.5.2 - Clear Cache now cleans up jellyfin.db
  - FIX: Clear Cache button now triggers Jellyfin channel refresh after invalidating plugin cache
  - EFFECT: When cache is cleared, plugin falls back to API, Jellyfin updates jellyfin.db with fresh data
  - EFFECT: Orphaned items in jellyfin.db are removed when they no longer exist in API response
  - Full cache clear cycle: Plugin cache cleared → Jellyfin refresh → API fetch → DB updated
