---
name: "Jellyfin Xtream (Flat View)"
guid: "5d774c35-8567-46d3-a950-9bb8227a0c5d"
version: "0.9.4.12"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Stream content from an Xtream-compatible server with flat series and VOD view."
description: >
  Stream Live IPTV, Video On-Demand, and Series from an Xtream-compatible server using this plugin.
  Includes flat series view and flat VOD view features to show all content directly without category folders.
category: "LiveTV"
owner: "Kevinjil"
artifacts:
  - "Jellyfin.Xtream.dll"
changelog: >
  v0.9.4.12 - Fix Clear Cache Not Stopping Cache Refresh
  - FIXED: Clear Cache button now properly stops ongoing cache refresh operations
  - Added explicit cancellation checks in the refresh loop for faster response
  - Status immediately shows "Cancelling..." when Clear Cache is clicked
  - Cache refresh now stops within seconds instead of continuing for minutes
